[10.0] migrate all UNECE modules
OCA/community-data-files pull request #17
Opened 2016-11-19 00:52 UTC by alexis-via

2017-01-06 10:13 UTC, pedrobaeza commented
Can you please squash the history for removing meaningless commits?

2017-02-24 07:15 UTC, alexis-via commented
Squashed.

2017-02-24 08:08 UTC, pedrobaeza approved these changes

2017-02-24 11:46 UTC, tarteo requested changes
Thanks for the migration! I was not able to test account_payment_unece (see comment), otherwise 👍

2017-02-24 11:46 UTC, tarteo commented on account_payment_unece/README.rst
> +Go to the menu *Accounting > Configuration > Management > Payment Methods* and select the appropriate value for the *UNECE Code*.
I can't find this menu in Runbot.

2017-02-25 21:12 UTC, alexis-via commented on account_payment_unece/README.rst
> +Go to the menu *Accounting > Configuration > Management > Payment Methods* and select the appropriate value for the *UNECE Code*.
True. You need the module account_payment_mode to see this menu entry, but we don't depend on this module.

2017-02-26 18:25 UTC, tarteo approved these changes

2017-02-26 18:27 UTC, pedrobaeza commented on account_payment_unece/__manifest__.py
> +    'depends': ['account_payment_mode', 'base_unece'],
@alexis-via the dependency to `account_payment_mode` is here, so the comment is not correct.

2017-02-28 21:03 UTC, astirpe approved these changes

2017-03-16 12:58 UTC, alexis-via commented
Someone with commit rights to merge this ?

2017-03-17 00:58 UTC, pedrobaeza commented
Can I squash your commits?

2017-03-17 09:34 UTC, alexis-via commented
I squashed the 2 commits I made before my last squash !

2017-03-17 10:02 UTC, merged