[MIG] base_3166: Migration to 11.0
OCA/community-data-files pull request #29
Opened 2017-10-06 10:02 UTC by etobella

Migration of module. I also added a simple test.

2017-10-09 07:21 UTC, yajo approved these changes

2017-10-10 11:43 UTC, pedrobaeza requested changes
Please check https://github.com/OCA/community-data-files/issues/22 about a change in the library API

2017-10-10 11:43 UTC, pedrobaeza commented on base_iso3166/tests/__init__.py
> +from . import test_iso3166
Line at the end

2017-10-10 11:49 UTC, etobella commented
@pedrobaeza, the requested change was done on 10.0 Migration: #25

2017-10-10 11:51 UTC, pedrobaeza commented
Ah, OK, thanks

2017-10-10 11:51 UTC, pedrobaeza approved these changes

2017-10-10 12:03 UTC, JordiBForgeFlow approved these changes
:+1: Functional and technical review

2017-10-10 12:03 UTC, jbeficent commented
3 approvals. This one can be merged!

2017-10-10 12:06 UTC, merged