[13.0][MIG] base_unece
OCA/community-data-files pull request #73
Opened 2019-10-23 08:49 UTC by astirpe

2019-10-23 09:50 UTC, pedrobaeza requested changes
You should promote this module to development status "Production/Stable" and you as maintainer IMO.

Please also squash administrative some commits together, like stated in the migration guide https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

2019-10-23 09:50 UTC, pedrobaeza commented on base_unece/static/description/index.html
> +<meta name="generator" content="Docutils 0.14: http://docutils.sourceforge.net/" />
Please update your local docutils to the same pinned version that is being used in OCA

2019-10-23 10:38 UTC, astirpe commented
Yep :+1: done.

2019-10-23 11:12 UTC, pedrobaeza approved these changes

2019-12-16 10:46 UTC, CasVissers-360ERP approved these changes
LGTM, functional review.

2019-12-16 11:52 UTC, pedrobaeza commented
/ocabot merge

2019-12-16 12:30 UTC, pedrobaeza commented
/ocabot merge

2019-12-16 13:35 UTC, merged