[12.0][MIG] product_fao_fishing
OCA/community-data-files pull request #75
Opened 2019-10-29 20:42 UTC by ernestotejeda

Cc @Tecnativa TT20174

2019-10-30 11:36 UTC, pedrobaeza requested changes
You must add a migration script that recomputes the parent_path. See the point in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0 about that

2019-10-30 11:36 UTC, pedrobaeza commented on product_fao_fishing/models/product_fao_fishing_technique.py
> -    _order = 'parent_left'
_order = 'parent_path'

2019-10-30 11:36 UTC, pedrobaeza commented on product_fao_fishing/models/product_fao_fishing_technique.py
>      _parent_order = 'name'
You can remove this line

2019-10-30 14:26 UTC, ernestotejeda commented
Changes done

2019-10-30 18:47 UTC, pedrobaeza approved these changes

2019-11-06 21:26 UTC, sergio-teruel approved these changes

2019-11-06 23:11 UTC, pedrobaeza commented
/ocabot merge

2019-11-06 23:22 UTC, merged