[IMP] l10n_eu_nace: add secondary
OCA/community-data-files pull request #90
Opened 2020-06-25 12:16 UTC by Yajo

Some need to add secondary NACE codes to partners.

This is a very little addition, possibly quite standard, so it's done directly in the base addon.

@Tecnativa TT17678

2020-06-25 13:26 UTC, sbejaoui approved these changes

2020-06-25 14:07 UTC, pedrobaeza requested changes

2020-06-25 14:07 UTC, pedrobaeza commented on l10n_eu_nace/views/res_partner.xml
> +                <field name="secondary_nace_ids"/>
Use `widget="many2many_tags"`

2020-06-26 07:10 UTC, Yajo commented on l10n_eu_nace/views/res_partner.xml
> +                <field name="secondary_nace_ids"/>
Changed.

2020-06-26 07:29 UTC, pedrobaeza approved these changes

2020-06-26 07:29 UTC, pedrobaeza commented
/ocabot merge minor

2020-06-26 08:07 UTC, merged